### ISSUE TITLE
Use data sources with placeholder parameters for external APIs

### ISSUE THREAD

**Issue by LeslieOA** [dadi/web#73] opened 2016-07-12 15:16 UTC
### Overview

There currently isn't a simple way to query external RESTful API or web services via HTTP path components or URL params with placeholders.

### Motivation or Use Case

To use datasources to query data from an external RESTful APIs/web services via HTTP URL parameters (query components) or path components.

Say for example, a user wanted to use a data source to pass both dynamic placeholders `genre` and `year` to their external API. There is currently no simple way using data sources `requestParams` to achieve this.

### DADI Web Version
1.4.1

### Operating System(s)

- Mac OS X 10.12 - Darwin Kernel Version 16.0.0; root:xnu-3757.0.0.0.1~20/RELEASE_X86_64 x86_64
- Ubuntu 14.04.4 - Linux 3.13.0-74-generic #118-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

### Steps to Reproduce 

1. Attempt to use a request parameter as a HTTP param (e.g. `/audio/?genre=witchhaus&year=2012`) or a path component (e.g. `/audio/witchaus/2012/`) in data source.

### Suggested Fix?

I've been informed that [events](https://github.com/dadi/docs/blob/master/web/concepts/events.md) can cover this for the meantime, but I'm hoping this would/could be an extension of issue #52. 

An uneducated suggestion, possibly using a new key `requestType` or `remoteRequestType` for a boolean. Discuss. 

```json
{
  "datasource": {
    "key": "core_business_api",
    "name": "The API powering all of our businesses apps",
    "source": {
      "type": "remote",
      "protocol": "http",
      "host": "blank.audio",
      "port": "80",
      "endpoint": "4.4/audio/"
    },
    "auth": {
      "type": "bearer",
      "host": "blank.audio",
      "port": "80",
      "tokenUrl": "/token",
      "credentials": {
        "clientId": "blank-audio",
        "secret": "C1iPLKYra8ZDKb8p9sCjLhwNMSk/wkbYp1DOWqXhXwXIj1RFkh45PLSwt/GjNDNu"
      }
    },
    "caching": {
      "enabled": false,
      "ttl": 1800,
      "directory": "./cache/web/",
      "extension": "json"
    },
    "requestType": "remote",
    "requestParams": [
      { "param": "channel", "field": "publication.furl" }
    ]
  }
}
```

Thanks.

**Comment by jimlambie** [comment] 2016-07-14 02:16
Thanks for the issue @LeslieOA! Yes, this is something I believe we can cover with the work (in progress!) for #52. 

The main problem we face is obtaining access tokens for the external service, as every service has a different implementation. Currently, with data only coming from DADI API, it's easy to handle using the Client Credentials OAuth flow. With A.N. Other service, the authentication flow will most certainly be different.

To help us in the development of #52 and ensure that we cover the use case you raise here, can you give me any concrete information about how you access the external datasource? Feel free to email or Slack me rather posting any sensitive information in this ticket.

**Comment by jimlambie** [comment] 2016-07-18 01:49
Closing, duplicate of #52

**Closed by jimlambie** 2016-07-18 01:49 UTC
