### ISSUE TITLE
Support for HTTP/2

### ISSUE THREAD

**Issue by abovedave** [dadi/web#155] opened 2017-04-13 11:51 UTC
Now we have https support coming we should consider adding H2 support to Web. The main advantages are:

- All requests are downloaded in parallel, not in a queue
- HTTP headers are compressed
- Pages transfer as a binary, not as a text file, which is more efficient
- Servers can “push” data even without the user’s request, which improves speed for users with high latency

Resources:

1. [Browser support info](http://caniuse.com/#feat=http2)
2. [Google Lighthouse recommendation](https://developers.google.com/web/tools/lighthouse/audits/http2)
3. [node-http2 node (with a similar api to node-http)](https://github.com/molnarg/node-http2)

**Comment by abovebored** [comment] 2017-05-08 10:33
# Current status

I have started using the [http2](https://github.com/molnarg/node-http2) module mentioned previously and it has taken well as a drop in replacement to the existing `https` module without much work. On `feature/http2` you can see this in action when using a SSL configuration (we use `http2` if the `protocol` is `https` and `http2` is `true`)

```JSON
"server": {
  "host": "example.com",
  "port": 443,
  "protocol": "https",
  "sslPrivateKeyPath": "keys/server.key",    
  "sslCertificatePath": "keys/server.crt",
  "http2": true
}
```

So straight away we have support for most of the benefits (multiplexing, binary transfers, header compression) and is backwards compatible with clients that do not support it 🎉

# Pushing assets

This is where it gets more complicated, but much cooler. Rather than _Web_ needing to wait for the client to parse a page and request specific images, FE javascript and CSS, we can _push_ these _before_ they request them. We just need a way to define this.

![zzecrfpyxi9ui](https://cloud.githubusercontent.com/assets/649231/25800662/25053a60-33e2-11e7-8bf2-2b27c639312a.gif)

## Asset manifests

As with most optimisation, we want to pick stuff that we know is going to be requested more often. I think following the [event](http://docs.dadi.tech/web/concepts/events/) structure might work nicely:

### globalPushManifest

An object placed in the `config.json` which is used for every request received by _Web_:

```JSON
"globalPushManifest": {
  "/main.js": {
    "type": "script",
    "weight": 1
  },
  "/styles.css": {
    "type": "style",
    "weight": 1
  },
  "/logo.png": {
    "type": "image",
    "weight": 1
  }
}
```

N.B. This format is based on an idea by the [Google Chrome team](https://github.com/GoogleChrome/http2-push-manifest).

N.B. 2.0 `weight` is a priority definition and not supported by any browser _yet_, but can be passed anyway for future use.

### pushManifest

Like the above, placed in a `page.json` definition file:

```JSON
"pushManifest": {
  "unicorns.jpg": {
    "type": "image",
    "weight": 1
  }
}
```

So for this page it would get the global + page level assets pushed on request.

### Existing asset serving

Right now we’re using the Express [serve-static](https://github.com/expressjs/serve-static) middleware to match up requests to the `public` folder with assets in them. **I’ve confirmed this still works with `http2`.**

We need to test what the browser behaviour here would be, but I assume we need to keep a record as to which assets have been pushed and which can be requested in the old-school way. It could be the case the browser knows not to request an asset again if it’s been pushed.

# Page parsing

I think this links in nicely to our aspirations of #141 and #103 - _Web_ being more aware of what is contained within template files.

If on boot we could go through every available page and calculate which assets from the `public` folder are required, our asset manifest could be generated internally.

# A note on [DADI CDN](https://github.com/dadi/cdn)

I don’t see why CDN should not be upgraded to use http2 as well, but as far as I understand we cannot do asset pushing with the same elegance as we can do in _Web_ because it will be a different server running _CDN_.

Perhaps there could be some way for _Web_ to pass its asset manifest to _CDN_ on boot? A push asset API? _CDN_ could match up referral headers with an URL structure of some kind? [CloudFlare](https://blog.cloudflare.com/announcing-support-for-http-2-server-push-2/) offer this by I assume crawling/reading and caching assets ahead of time.

# Questions

- Does this sound like built in middleware, or does it need to go deeper as we need to parse `page.json` files? @james where would you put this?
- Is page parsing for now or later?

**Comment by eduardoboucas** [comment] 2017-05-09 09:42
This is awesome! I like the idea of global + page-level manifests. Could we perhaps make the syntax a bit shorter? For example, could we infer the `type` property from file extension? Could it simply be:

```json
"globalPushManifest": [
  "/main.js",
  "/styles.css",
  "/logo.png"
]
```

... depending on how we approach the `weight` property.

Page parsing is a cool idea. I think it should happen as a background task, and not as part of the request flow (i.e. we should never wait for the page to be parsed before pushing stuff to the client). Maybe this could be part of the monitor/watch routine: when a template changes, we parse it and add any assets to that page's manifest.

**Comment by abovebored** [comment] 2017-08-09 15:03
Closing, see #167

**Comment by abovedave** [comment] 2018-06-08 16:44
Digging up the past! Node 8 http2 support is there (related CDN ticket #373)

**Comment by abovedave** [comment] 2018-06-11 09:55
Would also be cool to add HTTP2 client support for communication between API and Web

**Closed** 2019-04-15 14:36 UTC
Labels: status: in progress, type: discussion
